apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: apprise-secrets
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: rke2-cluster
  config: main
  secrets:
    - TELEGRAM_BOT_TOKEN
    - TELEGRAM_CHAT_ID
  processors:
    TELEGRAM_BOT_TOKEN:
      type: plain
      asName: TELEGRAM_BOT_TOKEN
    TELEGRAM_CHAT_ID:
      type: plain
      asName: TELEGRAM_CHAT_ID
  managedSecret:
    name: apprise-secrets
    namespace: apprise
    type: Opaque
