apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
  namespace: dashy
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dashy
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
        - name: dashy
          image: lissy93/dashy@sha256:8166e7e269abbe8e9244748a1a3fb8070d934cfa3f7d121e68084b9b16c8594b # v3.2.4
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
            - name: TZ
              value: Asia/Kolkata
          volumeMounts:
            - name: user-data
              mountPath: /app/user-data
          startupProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            failureThreshold: 18
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 60
          resources:
            requests:
              memory: 512Mi
              cpu: 100m
            limits:
              memory: 2Gi
              cpu: "2"
      volumes:
        - name: user-data
          persistentVolumeClaim:
            claimName: dashy-config
