apiVersion: v1
kind: Namespace
metadata:
  name: wg-gateway
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: wg-jellyfin-doppler
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: rke2-cluster
  config: main
  secrets:
    - WG_JELLYFIN_HOME_PRIVATE_KEY
  managedSecret:
    name: wg-jellyfin-doppler
    namespace: wg-gateway
    type: Opaque
