apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: reddit-mcp-basic-auth
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: rke2-cluster
  config: main
  secrets:
    - SEARXNG_BASIC_AUTH_HTPASSWD
  processors:
    SEARXNG_BASIC_AUTH_HTPASSWD:
      type: plain
      asName: auth
  managedSecret:
    name: reddit-mcp-basic-auth
    namespace: reddit-mcp
    type: Opaque
