apiVersion: v1
kind: Service
metadata:
  name: silo
  namespace: silo
spec:
  type: ClusterIP
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  selector:
    app: silo
  ports:
    - name: http
      port: 8080
      targetPort: http
