apiVersion: v1
kind: Namespace
metadata:
  name: silo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silo-data
  namespace: silo
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/default: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: silo-cache
  namespace: silo
  labels:
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/cache-no-backup: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-cache
  volumeMode: Filesystem
  resources:
    requests:
      # Node 3 currently advertises about 14.6Gi for this cache class.
      storage: 10Gi
