apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: master-project
  namespace: default
spec:
  sourceRepos:
    - "git@github.com:kavishwar-khankari/kubernetes-homelab.git"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
