apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: grafana-secrets
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system

  project: rke2-cluster
  config: main

  secrets:
    - GRAFANA_ADMIN_USER
    - GRAFANA_ADMIN_PASSWORD

  processors:
    GRAFANA_ADMIN_USER:
      type: plain
      asName: admin-user
    GRAFANA_ADMIN_PASSWORD:
      type: plain
      asName: admin-password

  managedSecret:
    name: grafana-secrets
    namespace: monitoring
    type: Opaque
