apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: minio-secrets
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system

  project: rke2-cluster
  config: main

  secrets:
    - MINIO_ROOT_USER
    - MINIO_ROOT_PASSWORD

  processors:
    MINIO_ROOT_USER:
      type: plain
      asName: root-user
    MINIO_ROOT_PASSWORD:
      type: plain
      asName: root-password

  managedSecret:
    name: minio-secrets
    namespace: monitoring
    type: Opaque
