apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-serve-config
  namespace: minecraft
data:
  serve.json: |
    {
      "TCP": {
        "25565": {
          "TCPForward": "127.0.0.1:25566"
        }
      }
    }