annotations:
  artifacthub.io/category: networking
  artifacthub.io/changes: |
    - kind: changed
      description: "Bump Chart version to 1.5.0 and Chart AppVersion to Newt v1.12.5."
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: newt-dockerhub
      image: docker.io/fosrl/newt:1.12.5
      whitelisted: false
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
    - name: newt-ghcr
      image: ghcr.io/fosrl/newt:1.12.5
      whitelisted: false
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm/v7
  artifacthub.io/license: MIT
  artifacthub.io/links: |
    - name: support
      url: https://github.com/fosrl/helm-charts/issues
    - name: documentation
      url: https://docs.digpangolin.com/self-host/manual/kubernetes
  artifacthub.io/prerelease: "false"
  artifacthub.io/signKey: |
    fingerprint: 48E7F670FCC13645FC48B08D587294B228C2EC2C
    url: https://charts.fossorial.io/pgp_keys.asc
apiVersion: v2
appVersion: 1.12.5
description: Helm chart to deploy Newt (fosrl/newt) client instance
home: https://digpangolin.com/
icon: https://raw.githubusercontent.com/fosrl/pangolin/refs/heads/main/public/logo/pangolin_orange.svg
keywords:
- newt
- pangolin
- vpn
- wireguard
- networking
kubeVersion: '>=1.30.14-0'
maintainers:
- email: info@marcschaeferger.de
  name: marcschaeferger
  url: https://github.com/marcschaeferger
name: newt
sources:
- https://github.com/fosrl/helm-charts
- https://github.com/fosrl/newt
type: application
version: 1.5.0
