apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: perry-zen
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: rke2-cluster
  config: main
  secrets:
    - PERRY_ZEN_API_KEY
  managedSecret:
    name: perry-secrets
    namespace: perry
    type: Opaque
