apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openchamber-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx-private
  tls:
    - hosts:
        - openchamber.techtronics.top
  rules:
    - host: openchamber.techtronics.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openchamber-service
                port:
                  name: http
