apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: homepage-secrets
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: rke2-cluster
  config: main
  secrets:
    - HOMEPAGE_SONARR_API_KEY
    - HOMEPAGE_RADARR_API_KEY
    - HOMEPAGE_PROWLARR_API_KEY
    - HOMEPAGE_JELLYFIN_API_KEY
    - HOMEPAGE_JELLYSEERR_API_KEY
    - HOMEPAGE_QBITTORRENT_USER
    - HOMEPAGE_QBITTORRENT_PASS
    - HOMEPAGE_ADGUARD_USER
    - HOMEPAGE_ADGUARD_PASS
    - HOMEPAGE_GRAFANA_TOKEN
    - HOMEPAGE_PVE1_TOKEN
    - HOMEPAGE_PVE2_TOKEN
    - HOMEPAGE_PVE3_TOKEN
    - HOMEPAGE_PVE4_TOKEN
    - HOMEPAGE_PVE11_TOKEN
    - HOMEPAGE_PBS_TOKEN
    - HOMEPAGE_PBS11_TOKEN
    - HOMEPAGE_TRUENAS_API_KEY
    - HOMEPAGE_PORT_0_API_KEY
    - HOMEPAGE_PORT_1_API_KEY
  processors:
    HOMEPAGE_SONARR_API_KEY:
      type: plain
      asName: HOMEPAGE_VAR_SONARR_API_KEY
    HOMEPAGE_RADARR_API_KEY:
      type: plain
      asName: HOMEPAGE_VAR_RADARR_API_KEY
    HOMEPAGE_PROWLARR_API_KEY:
      type: plain
      asName: HOMEPAGE_VAR_PROWLARR_API_KEY
    HOMEPAGE_JELLYFIN_API_KEY:
      type: plain
      asName: HOMEPAGE_VAR_JELLYFIN_API_KEY
    HOMEPAGE_JELLYSEERR_API_KEY:
      type: plain
      asName: HOMEPAGE_VAR_JELLYSEERR_API_KEY
    HOMEPAGE_QBITTORRENT_USER:
      type: plain
      asName: HOMEPAGE_VAR_QBITTORRENT_USER
    HOMEPAGE_QBITTORRENT_PASS:
      type: plain
      asName: HOMEPAGE_VAR_QBITTORRENT_PASS
    HOMEPAGE_ADGUARD_USER:
      type: plain
      asName: HOMEPAGE_VAR_ADGUARD_USER
    HOMEPAGE_ADGUARD_PASS:
      type: plain
      asName: HOMEPAGE_VAR_ADGUARD_PASS
    HOMEPAGE_GRAFANA_TOKEN:
      type: plain
      asName: HOMEPAGE_VAR_GRAFANA_TOKEN
    HOMEPAGE_PVE1_TOKEN:
      type: plain
      asName: HOMEPAGE_VAR_PVE1_TOKEN
    HOMEPAGE_PVE2_TOKEN:
      type: plain
      asName: HOMEPAGE_VAR_PVE2_TOKEN
    HOMEPAGE_PVE3_TOKEN:
      type: plain
      asName: HOMEPAGE_VAR_PVE3_TOKEN
    HOMEPAGE_PVE4_TOKEN:
      type: plain
      asName: HOMEPAGE_VAR_PVE4_TOKEN
    HOMEPAGE_PVE11_TOKEN:
      type: plain
      asName: HOMEPAGE_VAR_PVE11_TOKEN
    HOMEPAGE_PBS_TOKEN:
      type: plain
      asName: HOMEPAGE_VAR_PBS_TOKEN
    HOMEPAGE_PBS11_TOKEN:
      type: plain
      asName: HOMEPAGE_VAR_PBS11_TOKEN
    HOMEPAGE_TRUENAS_API_KEY:
      type: plain
      asName: HOMEPAGE_VAR_TRUENAS_API_KEY
    HOMEPAGE_PORT_0_API_KEY:
      type: plain
      asName: HOMEPAGE_VAR_PORT_0_API_KEY
    HOMEPAGE_PORT_1_API_KEY:
      type: plain
      asName: HOMEPAGE_VAR_PORT_1_API_KEY
  managedSecret:
    name: homepage-secrets
    namespace: homepage
    type: Opaque
