apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: tachidesk-secrets
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: rke2-cluster
  config: main
  secrets:
    - TACHIDESK_AUTH_USERNAME
    - TACHIDESK_AUTH_PASSWORD
  processors:
    TACHIDESK_AUTH_USERNAME:
      type: plain
      asName: AUTH_USERNAME
    TACHIDESK_AUTH_PASSWORD:
      type: plain
      asName: AUTH_PASSWORD
  managedSecret:
    name: tachidesk-secrets
    namespace: tachidesk
    type: Opaque
