apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: jellyfin-meilisearch-secrets
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: rke2-cluster
  config: main
  secrets:
    - MEILI_MASTER_KEY
  processors:
    MEILI_MASTER_KEY:
      type: plain
      asName: MEILI_MASTER_KEY
  managedSecret:
    name: jellyfin-meilisearch-secrets
    namespace: jellyfin
    type: Opaque
