apiVersion: v1
kind: Namespace
metadata:
  name: jellyfin
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-cache
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  fsType: ext4
  dataLocality: best-effort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 150Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-data
  namespace: jellyfin
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  namespace: jellyfin
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn-cache
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media2-media-pv
spec:
  capacity:
    storage: 10Ti   # bookkeeping only; pick something roughly realistic for your NAS/share
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: jellyfin-media2-media   # must be unique cluster-wide
    volumeAttributes:
      source: "//192.168.0.75/media_2/media"
    nodeStageSecretRef:
      name: smbcreds
      namespace: jellyfin
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media2-media
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: jellyfin-media2-media-pv
  resources:
    requests:
      storage: 10Ti
