apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: openwebui-secrets
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: rke2-cluster
  config: main
  secrets:
    - OPENROUTER_API_KEY
  managedSecret:
    name: openwebui-secrets
    namespace: openwebui
    type: Opaque
