apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-to-nas
  namespace: longhorn-system
spec:
  cron: "0 23 * * ?"
  task: backup
  groups:
    - default
  retain: 7
  concurrency: 1
  parameters:
    full-backup-interval: "30"
