apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: truenas-portainer-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx-private
  tls:
    - hosts:
        - truenas-portainer.techtronics.top
  rules:
    - host: truenas-portainer.techtronics.top
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: truenas-portainer-service
                port:
                  name: https
