apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: searxng-secrets
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: rke2-cluster
  config: main
  secrets:
    - SEARXNG_SECRET_KEY
  managedSecret:
    name: searxng-secrets
    namespace: searxng
    type: Opaque
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: searxng-basic-auth
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: rke2-cluster
  config: main
  secrets:
    - SEARXNG_BASIC_AUTH_HTPASSWD
  processors:
    SEARXNG_BASIC_AUTH_HTPASSWD:
      type: plain
      asName: auth
  managedSecret:
    name: searxng-basic-auth
    namespace: searxng
    type: Opaque
