apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: arr-gate-api-keys
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system

  project: rke2-cluster
  config: main

  secrets:
    - SONARR_API_KEY_
    - RADARR_API_KEY

  processors:
    SONARR_API_KEY_:
      type: plain
      asName: ARR_GATE_SONARR_API_KEY
    RADARR_API_KEY:
      type: plain
      asName: ARR_GATE_RADARR_API_KEY

  managedSecret:
    name: arr-gate-api-keys
    namespace: tdarr
    type: Opaque
