{{- if .Values.dopplerSecret.enabled }}
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: {{ required "dopplerSecret.name is required when enabled" .Values.dopplerSecret.name }}
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: {{ required "dopplerSecret.project is required when enabled" .Values.dopplerSecret.project }}
  config: {{ required "dopplerSecret.config is required when enabled" .Values.dopplerSecret.config }}
  secrets:
    {{- range .Values.dopplerSecret.secrets }}
    - {{ .name }}
    {{- end }}
  processors:
    {{- range .Values.dopplerSecret.secrets }}
    {{ .name }}:
      type: plain
      asName: {{ .asName }}
    {{- end }}
  managedSecret:
    name: {{ required "dopplerSecret.managedSecret.name is required when enabled" .Values.dopplerSecret.managedSecret.name }}
    namespace: {{ .Release.Namespace }}
    type: kubernetes.io/basic-auth
{{- end }}
