apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: frostbite-secrets
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: rke2-cluster
  config: main
  secrets:
    - FROSTBITE_DATABASE_URL
    - JELLYFIN_API_KEY
    - SONARR_API_KEY
    - RADARR_API_KEY
  processors:
    FROSTBITE_DATABASE_URL:
      type: plain
      asName: DATABASE_URL
    JELLYFIN_API_KEY:
      type: plain
      asName: JELLYFIN_API_KEY
    SONARR_API_KEY:
      type: plain
      asName: SONARR_API_KEY
    RADARR_API_KEY:
      type: plain
      asName: RADARR_API_KEY
  managedSecret:
    name: frostbite-secrets
    namespace: frostbite
    type: Opaque
