apiVersion: v1
kind: Service
metadata:
  name: frostbite-service
  namespace: frostbite
spec:
  type: ClusterIP
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  selector:
    app: frostbite
  ports:
    - name: http
      port: 8000
      targetPort: 8000
