apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: rclone-secrets
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system

  project: rke2-cluster
  config: main

  secrets:
    - OPENDRIVE_USERNAME
    - OPENDRIVE_PASSWORD_OBSCURED
    - OPENDRIVE_CRYPT_PASSWORD_OBSCURED
    - RCLONE_GUI_USER
    - RCLONE_GUI_PASS

  managedSecret:
    name: rclone-secrets
    namespace: rclone
    type: Opaque
