apiVersion: v1
kind: Namespace
metadata:
  name: paperless
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
  namespace: paperless
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-consume
  namespace: paperless
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: paperless-big-data-pv
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: paperless-big-data
    volumeAttributes:
      source: "//192.168.0.75/big_data"
    nodeStageSecretRef:
      name: smbcreds-paperless
      namespace: paperless
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - noperm
    - mfsymlinks
    - cache=strict
    - noserverino
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-big-data
  namespace: paperless
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: paperless-big-data-pv
  resources:
    requests:
      storage: 10Ti
