apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: ovms-api-key
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: rke2-cluster
  config: main
  secrets:
    - OVMS_API_KEY
  managedSecret:
    name: ovms-api-key
    namespace: ovms
    type: Opaque
