apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: vaultwarden-secrets
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: rke2-cluster
  config: main
  secrets:
    - VAULTWARDEN_ADMIN_TOKEN
  processors:
    VAULTWARDEN_ADMIN_TOKEN:
      type: plain
      asName: ADMIN_TOKEN
  managedSecret:
    name: vaultwarden-secrets
    namespace: vaultwarden
    type: Opaque
