apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data
  namespace: vaultwarden
  labels:
    recurring-job-group.longhorn.io/default: enabled
    recurring-job-group.longhorn.io/vaultwarden: enabled
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: vaultwarden-snapshot-hourly
  namespace: longhorn-system
spec:
  cron: "0 * * * *"
  task: snapshot
  groups:
    - vaultwarden
  retain: 24
  concurrency: 1
