apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-grafana
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: master-project
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 10.5.15
      helm:
        valueFiles:
          - $values/helm/monitoring-grafana/values.yaml
    - repoURL: https://github.com/kavishwar-khankari/kubernetes-homelab.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
