apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-node-exporter
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: master-project
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus-node-exporter
      targetRevision: 4.55.0
      helm:
        valueFiles:
          - $values/helm/monitoring-node-exporter/values.yaml
    - repoURL: https://github.com/kavishwar-khankari/kubernetes-homelab.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
