apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: newt
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: master-project
  destination:
    server: https://kubernetes.default.svc
    namespace: newt
  sources:
    - repoURL: https://github.com/kavishwar-khankari/kubernetes-homelab.git
      targetRevision: main
      path: helm/newt
      helm:
        releaseName: newt
        valueFiles:
          - homelab-values.yaml
    - repoURL: https://github.com/kavishwar-khankari/kubernetes-homelab.git
      targetRevision: main
      path: manifests/newt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
