apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: private-ingress
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: master-project
  destination:
    server: https://kubernetes.default.svc
    namespace: private-ingress
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.13.4
      helm:
        releaseName: private-ingress-nginx
        valueFiles:
          - $values/helm/private-ingress/values.yaml
    - repoURL: https://github.com/kavishwar-khankari/kubernetes-homelab.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
