apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: reverse-proxy
  namespace: default
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/kavishwar-khankari/kubernetes-homelab.git
        revision: main
        directories:
          - path: reverse-proxy/*
  syncPolicy:
    orphan:
      enabled: true
      preserveResourcesOnDeletion: false
  template:
    metadata:
      name: "rp-{{ .path.basenameNormalized }}"
    spec:
      project: master-project
      source:
        repoURL: https://github.com/kavishwar-khankari/kubernetes-homelab.git
        targetRevision: main
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .path.basenameNormalized }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
